<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="21.48s"
		durationms="21480"
		type="root"
		rid="729194d8f6ec44c"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Admin"
		rxversion="10.2.3.0"
		host="ADMIN"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="en-US"
		dtnlanguage="en-US"
		screenresolution="1920x1080"
		timestamp="29/8/2022 10:30:42 AM"
		timestampiso="2022-08-29T03:30:42"
		endtime="29/8/2022 10:31:03 AM"
		timeoutfactor="1"
		runid=""
		sutversion=""
		module="RecordingBuy1">
		<detail>
			RecordingBuy1
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:21.476"
			timeRelativeToTestModuleStartTime="00:21.476"
			timeWallClock="10:31:03"
			time="00:21.476"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
